# Generated by Django 4.2.4 on 2024-04-14 05:05

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dep_mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(verbose_name=django.contrib.auth.models.User)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='perfil/', verbose_name='Imagen de Perfil')),
                ('usuario_activo', models.BooleanField(default=True)),
                ('carrera', models.CharField(blank=True, max_length=200, null=True, verbose_name='Carrera')),
                ('rol', models.CharField(max_length=40, verbose_name='Rol')),
            ],
            options={
                'db_table': 'userDep',
            },
        ),
        migrations.CreateModel(
            name='jefDepartamento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidosPaterno', models.CharField(max_length=50)),
                ('apellidosMaterno', models.CharField(max_length=50)),
                ('departamento', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'jefDepartamento',
            },
        ),
        migrations.CreateModel(
            name='jefMantenimiento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidosPaterno', models.CharField(max_length=50)),
                ('apellidosMaterno', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'jefMantenimiento',
            },
        ),
        migrations.CreateModel(
            name='solicitante',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidosPaterno', models.CharField(max_length=50)),
                ('apellidosMaterno', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'solicitante',
            },
        ),
        migrations.CreateModel(
            name='subdirectora',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidosPaterno', models.CharField(max_length=50)),
                ('apellidosMaterno', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'subdirectora',
            },
        ),
        migrations.CreateModel(
            name='trabajadores',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidosPaterno', models.CharField(max_length=50)),
                ('apellidosMaterno', models.CharField(max_length=50)),
                ('num_solicitudes', models.IntegerField()),
            ],
            options={
                'db_table': 'trabajadores',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('folio', models.IntegerField()),
                ('area_solicitante', models.CharField(max_length=50)),
                ('responsable_Area', models.CharField(max_length=50)),
                ('tipo_servicio', models.CharField(choices=[('Cañones', 'Cañones'), ('Pintura', 'Pintura'), ('Plomería', 'Plomería'), ('Herrería', 'Herrería'), ('Cerrajería', 'Cerrajería'), ('Electrica', 'Electrica'), ('Otro', 'Otro'), ('Pintarrón', 'Pintarrón')], max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('des_Serv_Realizado', models.CharField(max_length=50)),
                ('des_Serv_no_Realizado', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Rechazada', 'Rechazada'), ('En proceso', 'En proceso'), ('En espera', 'En espera'), ('Pendiente', 'Pendiente'), ('Cancelada', 'Cancelada'), ('Realizada', 'Realizada')], max_length=50)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('material_utilizado', models.CharField(max_length=50, null=True)),
                ('imagen', models.FileField(null=True, upload_to='dep_mantenimiento/img')),
                ('motv_rechazo', models.CharField(max_length=50, null=True)),
                ('jefDepartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dep_mantenimiento.jefdepartamento')),
                ('jefMantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dep_mantenimiento.jefmantenimiento')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dep_mantenimiento.solicitante')),
                ('subdirectora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dep_mantenimiento.subdirectora')),
                ('trabajadores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dep_mantenimiento.trabajadores')),
            ],
            options={
                'db_table': 'solicitudes',
            },
        ),
        migrations.AddField(
            model_name='jefmantenimiento',
            name='trabajadores',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dep_mantenimiento.trabajadores'),
        ),
    ]
