# Generated by Django 4.2.4 on 2024-05-04 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trabajadores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.PositiveIntegerField(blank=True, null=True)),
                ('nombres', models.CharField(blank=True, db_column='nombres', max_length=40, null=True, verbose_name='Nombre(s)')),
                ('appaterno', models.CharField(blank=True, db_column='appaterno', max_length=40, null=True, verbose_name='Apellido Paterno')),
                ('apmaterno', models.CharField(blank=True, db_column='apmaterno', max_length=40, null=True, verbose_name='Apellido Materno')),
                ('activo', models.CharField(blank=True, choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], db_column='activo', default='activo', max_length=15, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('H', 'Hombre'), ('M', 'Mujer')], db_column='sexo', max_length=1, null=True, verbose_name='Sexo')),
                ('puesto', models.CharField(blank=True, choices=[('Subdirector', 'Subdirector/a'), ('Jefe', 'Jefe'), ('Secretario', 'Secretario/a'), ('Empleado', 'Empleado'), ('Docente', 'Docente')], max_length=100, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('campus', models.PositiveIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, db_column='email', max_length=100, null=True, verbose_name='Correo')),
                ('foto_Perfil', models.ImageField(blank=True, null=True, upload_to='dep_mantenimiento/img/Foto_Perfil', verbose_name='Imagen de Perfil')),
            ],
            options={
                'verbose_name': 'Perfil de trabajador',
                'db_table': 'trabajador',
            },
        ),
        migrations.CreateModel(
            name='Solicitud_Mantenimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.IntegerField(blank=True)),
                ('area_solicitante', models.CharField(blank=True, max_length=150)),
                ('responsable_Area', models.CharField(blank=True, max_length=300)),
                ('tipo_servicio', models.CharField(blank=True, choices=[('Cerrajería', 'Cerrajería'), ('Pintarrón', 'Pintarrón'), ('Cañones', 'Cañones'), ('Otro', 'Otro'), ('Herrería', 'Herrería'), ('Electrica', 'Electrica'), ('Plomería', 'Plomería'), ('Pintura', 'Pintura')], max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=3000)),
                ('des_Serv_Realizado', models.CharField(blank=True, max_length=3000, null=True)),
                ('des_Serv_no_Realizado', models.CharField(blank=True, max_length=3000, null=True)),
                ('status', models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Rechazado', 'Rechazado'), ('Enviado', 'Enviado'), ('En_proceso', 'En proceso'), ('Realizado', 'Realizado'), ('En_espera', 'En espera'), ('Alerta', 'Alerta')], max_length=50)),
                ('fecha', models.DateField(blank=True)),
                ('hora', models.TimeField(blank=True)),
                ('material_asignado', models.CharField(blank=True, max_length=3000, null=True)),
                ('material_utilizado', models.CharField(blank=True, max_length=3000, null=True)),
                ('imagen', models.FileField(blank=True, null=True, upload_to='dep_mantenimiento/img')),
                ('motv_rechazo', models.CharField(blank=True, max_length=3000, null=True)),
                ('firma_Jefe_Departamento', models.BooleanField(blank=True, default=False)),
                ('firma_Empleado', models.BooleanField(blank=True, default=False)),
                ('firma_Jefe_Mantenimiento', models.BooleanField(blank=True, default=False)),
                ('firma_Jefe_Departamento_img', models.ImageField(blank=True, null=True, upload_to='dep_mantenimiento/img')),
                ('firma_Empleado_img', models.ImageField(blank=True, null=True, upload_to='dep_mantenimiento/img')),
                ('firma_Jefe_Mantenimiento_img', models.ImageField(blank=True, null=True, upload_to='dep_mantenimiento/img')),
                ('id_Empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_empleado', to='dep_mantenimiento.trabajadores')),
                ('id_Jefe_Departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_jefe_departamento', to='dep_mantenimiento.trabajadores')),
                ('id_Jefe_Mantenimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_jefe_mantenimiento', to='dep_mantenimiento.trabajadores')),
                ('id_Subdirectora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_subdirectora', to='dep_mantenimiento.trabajadores')),
                ('id_Trabajador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_trabajador', to='dep_mantenimiento.trabajadores')),
            ],
            options={
                'verbose_name': 'Solicitud_de_mantenimiento',
                'db_table': 'solicitud_mantenimiento',
            },
        ),
    ]
