# Generated by Django 4.2.4 on 2024-05-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dep_mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialsolicitud',
            name='nuevo_status',
            field=models.CharField(choices=[('En_proceso', 'En proceso'), ('En_espera', 'En espera'), ('Enviado', 'Enviado'), ('Realizado', 'Realizado'), ('Pendiente', 'Pendiente'), ('Rechazado', 'Rechazado'), ('Solicitud_Firmada', 'Firmado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitud_mantenimiento',
            name='firma_Empleado_img',
            field=models.ImageField(blank=True, null=True, upload_to='dep_mantenimiento/img/Firmas/Empleado'),
        ),
        migrations.AlterField(
            model_name='solicitud_mantenimiento',
            name='status',
            field=models.CharField(blank=True, choices=[('En_proceso', 'En proceso'), ('En_espera', 'En espera'), ('Enviado', 'Enviado'), ('Realizado', 'Realizado'), ('Pendiente', 'Pendiente'), ('Rechazado', 'Rechazado'), ('Solicitud_Firmada', 'Firmado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitud_mantenimiento',
            name='tipo_servicio',
            field=models.CharField(blank=True, choices=[('Cañones', 'Cañones'), ('Herrería', 'Herrería'), ('Cerrajería', 'Cerrajería'), ('Otro', 'Otro'), ('Electrica', 'Electrica'), ('Pintura', 'Pintura'), ('Pintarrón', 'Pintarrón'), ('Plomería', 'Plomería')], max_length=100),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='puesto',
            field=models.CharField(blank=True, choices=[('Docente', 'Docente'), ('Jefe', 'Jefe'), ('Subdirector', 'Subdirector/a'), ('Empleado', 'Empleado'), ('Secretario', 'Secretario/a')], max_length=100, null=True),
        ),
    ]
