# Generated by Django 4.2.4 on 2024-04-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dep_mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_mantenimiento',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='dep_mantenimiento/img'),
        ),
        migrations.AlterField(
            model_name='solicitud_mantenimiento',
            name='status',
            field=models.CharField(blank=True, choices=[('En proceso', 'En proceso'), ('Pendiente', 'Pendiente'), ('Cancelado', 'Cancelado'), ('Enviado', 'Enviado'), ('Rechazado', 'Rechazado'), ('En espera', 'En espera'), ('Realizado', 'Realizado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitud_mantenimiento',
            name='tipo_servicio',
            field=models.CharField(blank=True, choices=[('Pintarrón', 'Pintarrón'), ('Cañones', 'Cañones'), ('Pintura', 'Pintura'), ('Otro', 'Otro'), ('Plomería', 'Plomería'), ('Electrica', 'Electrica'), ('Cerrajería', 'Cerrajería'), ('Herrería', 'Herrería')], max_length=100),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='puesto',
            field=models.CharField(blank=True, choices=[('Empleado', 'Empleado'), ('Jefe', 'Jefe'), ('Docente', 'Docente'), ('Secretario', 'Secretario/a'), ('Subdirector', 'Subdirector/a')], max_length=100),
        ),
    ]
