# Generated by Django 4.2.4 on 2024-05-15 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dep_mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenesevidencias',
            options={'verbose_name': 'Evidencias'},
        ),
        migrations.AlterField(
            model_name='historialsolicitud',
            name='nuevo_status',
            field=models.CharField(choices=[('Realizado', 'Realizado'), ('En_espera', 'En espera'), ('Pendiente', 'Pendiente'), ('Enviado', 'Enviado'), ('En_proceso', 'En proceso'), ('Rechazado', 'Rechazado'), ('Solicitud_Firmada', 'Firmado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitud_mantenimiento',
            name='status',
            field=models.CharField(blank=True, choices=[('Realizado', 'Realizado'), ('En_espera', 'En espera'), ('Pendiente', 'Pendiente'), ('Enviado', 'Enviado'), ('En_proceso', 'En proceso'), ('Rechazado', 'Rechazado'), ('Solicitud_Firmada', 'Firmado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitud_mantenimiento',
            name='tipo_servicio',
            field=models.CharField(blank=True, choices=[('Pintura', 'Pintura'), ('Plomería', 'Plomería'), ('Cerrajería', 'Cerrajería'), ('Cañones', 'Cañones'), ('Herrería', 'Herrería'), ('Pintarrón', 'Pintarrón'), ('Electrica', 'Electrica'), ('Otro', 'Otro')], max_length=100),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='puesto',
            field=models.CharField(blank=True, choices=[('Empleado', 'Empleado'), ('Docente', 'Docente'), ('Jefe', 'Jefe'), ('Subdirector', 'Subdirector/a'), ('Secretario', 'Secretario/a')], max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='imagenesevidencias',
            table='Evidencias',
        ),
    ]
