# Generated by Django 4.2.4 on 2024-05-10 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dep_mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialsolicitud',
            name='hora',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='historialsolicitud',
            name='nuevo_status',
            field=models.CharField(choices=[('Realizado', 'Realizado'), ('Rechazado', 'Rechazado'), ('En_espera', 'En espera'), ('Enviado', 'Enviado'), ('Solicitud_Firmada', 'Firmado'), ('Pendiente', 'Pendiente'), ('En_proceso', 'En proceso')], max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitud_mantenimiento',
            name='status',
            field=models.CharField(blank=True, choices=[('Realizado', 'Realizado'), ('Rechazado', 'Rechazado'), ('En_espera', 'En espera'), ('Enviado', 'Enviado'), ('Solicitud_Firmada', 'Firmado'), ('Pendiente', 'Pendiente'), ('En_proceso', 'En proceso')], max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitud_mantenimiento',
            name='tipo_servicio',
            field=models.CharField(blank=True, choices=[('Otro', 'Otro'), ('Herrería', 'Herrería'), ('Pintura', 'Pintura'), ('Pintarrón', 'Pintarrón'), ('Plomería', 'Plomería'), ('Cañones', 'Cañones'), ('Cerrajería', 'Cerrajería'), ('Electrica', 'Electrica')], max_length=100),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='puesto',
            field=models.CharField(blank=True, choices=[('Subdirector', 'Subdirector/a'), ('Secretario', 'Secretario/a'), ('Docente', 'Docente'), ('Jefe', 'Jefe'), ('Empleado', 'Empleado')], max_length=100, null=True),
        ),
    ]
