# Generated by Django 4.2.4 on 2024-05-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dep_mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialsolicitud',
            name='nuevo_status',
            field=models.CharField(choices=[('Rechazado', 'Rechazado'), ('Realizado', 'Realizado'), ('Pendiente', 'Pendiente'), ('Enviado', 'Enviado'), ('Solicitud_Firmada', 'Firmado'), ('En_espera', 'En espera'), ('En_proceso', 'En proceso')], max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitud_mantenimiento',
            name='status',
            field=models.CharField(blank=True, choices=[('Rechazado', 'Rechazado'), ('Realizado', 'Realizado'), ('Pendiente', 'Pendiente'), ('Enviado', 'Enviado'), ('Solicitud_Firmada', 'Firmado'), ('En_espera', 'En espera'), ('En_proceso', 'En proceso')], max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitud_mantenimiento',
            name='tipo_servicio',
            field=models.CharField(blank=True, choices=[('Pintarrón', 'Pintarrón'), ('Herrería', 'Herrería'), ('Cañones', 'Cañones'), ('Electrica', 'Electrica'), ('Cerrajería', 'Cerrajería'), ('Plomería', 'Plomería'), ('Pintura', 'Pintura'), ('Otro', 'Otro')], max_length=100),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='puesto',
            field=models.CharField(blank=True, choices=[('Docente', 'Docente'), ('Secretario', 'Secretario/a'), ('Jefe', 'Jefe'), ('Empleado', 'Empleado'), ('Subdirector', 'Subdirector/a')], max_length=100, null=True),
        ),
    ]
