# Generated by Django 4.2.4 on 2024-04-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dep_mantenimiento', '0002_alter_solicitud_mantenimiento_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_mantenimiento',
            name='status',
            field=models.CharField(blank=True, choices=[('Enviado', 'Enviado'), ('Rechazado', 'Rechazado'), ('Cancelado', 'Cancelado'), ('En espera', 'En espera'), ('Realizado', 'Realizado'), ('En proceso', 'En proceso'), ('Pendiente', 'Pendiente')], max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitud_mantenimiento',
            name='tipo_servicio',
            field=models.CharField(blank=True, choices=[('Electrica', 'Electrica'), ('Plomería', 'Plomería'), ('Otro', 'Otro'), ('Herrería', 'Herrería'), ('Pintura', 'Pintura'), ('Cañones', 'Cañones'), ('Cerrajería', 'Cerrajería'), ('Pintarrón', 'Pintarrón')], max_length=100),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='puesto',
            field=models.CharField(blank=True, choices=[('Subdirector', 'Subdirector/a'), ('Jefe', 'Jefe'), ('Secretario', 'Secretario/a'), ('Docente', 'Docente'), ('Empleado', 'Empleado')], max_length=100),
        ),
    ]
