# Generated by Django 4.2.4 on 2024-05-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dep_mantenimiento', '0002_alter_imagenesevidencias_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud_mantenimiento',
            name='evidenciasIMG',
        ),
        migrations.AlterField(
            model_name='historialsolicitud',
            name='nuevo_status',
            field=models.CharField(choices=[('Solicitud_Firmada', 'Firmado'), ('En_espera', 'En espera'), ('Enviado', 'Enviado'), ('Realizado', 'Realizado'), ('En_proceso', 'En proceso'), ('Pendiente', 'Pendiente'), ('Rechazado', 'Rechazado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitud_mantenimiento',
            name='status',
            field=models.CharField(blank=True, choices=[('Solicitud_Firmada', 'Firmado'), ('En_espera', 'En espera'), ('Enviado', 'Enviado'), ('Realizado', 'Realizado'), ('En_proceso', 'En proceso'), ('Pendiente', 'Pendiente'), ('Rechazado', 'Rechazado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitud_mantenimiento',
            name='tipo_servicio',
            field=models.CharField(blank=True, choices=[('Pintura', 'Pintura'), ('Electrica', 'Electrica'), ('Pintarrón', 'Pintarrón'), ('Otro', 'Otro'), ('Cerrajería', 'Cerrajería'), ('Herrería', 'Herrería'), ('Plomería', 'Plomería'), ('Cañones', 'Cañones')], max_length=100),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='puesto',
            field=models.CharField(blank=True, choices=[('Secretario', 'Secretario/a'), ('Empleado', 'Empleado'), ('Docente', 'Docente'), ('Subdirector', 'Subdirector/a'), ('Jefe', 'Jefe')], max_length=100, null=True),
        ),
    ]
