# Generated by Django 4.2.4 on 2024-05-10 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dep_mantenimiento', '0003_alter_historialsolicitud_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialsolicitud',
            name='nuevo_status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Rechazado', 'Rechazado'), ('Enviado', 'Enviado'), ('En_proceso', 'En proceso'), ('En_espera', 'En espera'), ('Solicitud_Firmada', 'Firmado'), ('Realizado', 'Realizado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitud_mantenimiento',
            name='status',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Rechazado', 'Rechazado'), ('Enviado', 'Enviado'), ('En_proceso', 'En proceso'), ('En_espera', 'En espera'), ('Solicitud_Firmada', 'Firmado'), ('Realizado', 'Realizado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitud_mantenimiento',
            name='tipo_servicio',
            field=models.CharField(blank=True, choices=[('Pintura', 'Pintura'), ('Pintarrón', 'Pintarrón'), ('Cañones', 'Cañones'), ('Herrería', 'Herrería'), ('Plomería', 'Plomería'), ('Cerrajería', 'Cerrajería'), ('Electrica', 'Electrica'), ('Otro', 'Otro')], max_length=100),
        ),
    ]
