# Generated by Django 4.2.4 on 2024-05-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dep_mantenimiento', '0003_remove_solicitud_mantenimiento_evidenciasimg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialsolicitud',
            name='nuevo_status',
            field=models.CharField(choices=[('Realizado', 'Realizado'), ('En_espera', 'En espera'), ('Rechazado', 'Rechazado'), ('En_proceso', 'En proceso'), ('Enviado', 'Enviado'), ('Pendiente', 'Pendiente'), ('Solicitud_Firmada', 'Firmado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitud_mantenimiento',
            name='status',
            field=models.CharField(blank=True, choices=[('Realizado', 'Realizado'), ('En_espera', 'En espera'), ('Rechazado', 'Rechazado'), ('En_proceso', 'En proceso'), ('Enviado', 'Enviado'), ('Pendiente', 'Pendiente'), ('Solicitud_Firmada', 'Firmado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitud_mantenimiento',
            name='tipo_servicio',
            field=models.CharField(blank=True, choices=[('Cañones', 'Cañones'), ('Pintura', 'Pintura'), ('Cerrajería', 'Cerrajería'), ('Otro', 'Otro'), ('Herrería', 'Herrería'), ('Plomería', 'Plomería'), ('Pintarrón', 'Pintarrón'), ('Electrica', 'Electrica')], max_length=100),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='puesto',
            field=models.CharField(blank=True, choices=[('Subdirector', 'Subdirector/a'), ('Empleado', 'Empleado'), ('Docente', 'Docente'), ('Jefe', 'Jefe'), ('Secretario', 'Secretario/a')], max_length=100, null=True),
        ),
    ]
