# Generated by Django 4.2.4 on 2024-05-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dep_mantenimiento', '0004_alter_historialsolicitud_nuevo_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud_mantenimiento',
            old_name='firma_Jefe_Mantenimiento_img',
            new_name='firma_Jefe_VoBo_img',
        ),
        migrations.RemoveField(
            model_name='solicitud_mantenimiento',
            name='firma_Jefe_Mantenimiento',
        ),
        migrations.AddField(
            model_name='solicitud_mantenimiento',
            name='firma_Jefe_VoBo',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='historialsolicitud',
            name='nuevo_status',
            field=models.CharField(choices=[('En_espera', 'En espera'), ('Pendiente', 'Pendiente'), ('Rechazado', 'Rechazado'), ('Realizado', 'Realizado'), ('Enviado', 'Enviado'), ('Solicitud_Firmada', 'Firmado'), ('En_proceso', 'En proceso')], max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitud_mantenimiento',
            name='status',
            field=models.CharField(blank=True, choices=[('En_espera', 'En espera'), ('Pendiente', 'Pendiente'), ('Rechazado', 'Rechazado'), ('Realizado', 'Realizado'), ('Enviado', 'Enviado'), ('Solicitud_Firmada', 'Firmado'), ('En_proceso', 'En proceso')], max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitud_mantenimiento',
            name='tipo_servicio',
            field=models.CharField(blank=True, choices=[('Plomería', 'Plomería'), ('Cañones', 'Cañones'), ('Herrería', 'Herrería'), ('Pintura', 'Pintura'), ('Cerrajería', 'Cerrajería'), ('Pintarrón', 'Pintarrón'), ('Electrica', 'Electrica'), ('Otro', 'Otro')], max_length=100),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='puesto',
            field=models.CharField(blank=True, choices=[('Subdirector', 'Subdirector/a'), ('Jefe', 'Jefe'), ('Secretario', 'Secretario/a'), ('Empleado', 'Empleado'), ('Docente', 'Docente')], max_length=100, null=True),
        ),
    ]
