# Generated by Django 4.2.4 on 2024-05-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dep_mantenimiento', '0006_alter_historialsolicitud_nuevo_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialsolicitud',
            name='nuevo_status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En_proceso', 'En proceso'), ('Rechazado', 'Rechazado'), ('Realizado', 'Realizado'), ('Enviado', 'Enviado'), ('En_espera', 'En espera'), ('Solicitud_Firmada', 'Firmado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitud_mantenimiento',
            name='status',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('En_proceso', 'En proceso'), ('Rechazado', 'Rechazado'), ('Realizado', 'Realizado'), ('Enviado', 'Enviado'), ('En_espera', 'En espera'), ('Solicitud_Firmada', 'Firmado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitud_mantenimiento',
            name='tipo_servicio',
            field=models.CharField(blank=True, choices=[('Pintarrón', 'Pintarrón'), ('Herrería', 'Herrería'), ('Cerrajería', 'Cerrajería'), ('Electrica', 'Electrica'), ('Cañones', 'Cañones'), ('Plomería', 'Plomería'), ('Pintura', 'Pintura'), ('Otro', 'Otro')], max_length=100),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='puesto',
            field=models.CharField(blank=True, choices=[('Secretario', 'Secretario/a'), ('Jefe', 'Jefe'), ('Subdirector', 'Subdirector/a'), ('Empleado', 'Empleado'), ('Docente', 'Docente')], max_length=100, null=True),
        ),
    ]
