# Generated by Django 4.2.4 on 2023-09-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfa', '0011_auto_20210530_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_keys',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
